#With file-based (git, svn, and native) repositories, 
#resources with file names in application* (application.properties, application.yml, application-*.properties, and so on) are shared between all client applications. 
#You can use resources with these file names to configure global defaults and have them be overridden by application-specific files as necessary.

kinopoisk:
  tokens: 
    - CNRYSY9-B5Z4KH9-G5GXMT7-CEFFSXJ
    - A7B8BYM-WCP4S82-NK1P6NE-D4CEJB5
telegram:
  token: 7061516661:AAGh1FrWX_qkHcpGw86cv1OW_QN8ee6-lH0
  bot-username: "movie-match-bot"
